name: unused_assets_cli
description: A dart CLI to report and/or delete unused assets in a Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  mason_logger: ^0.3.2
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0

executables:
  unused_assets_cli:
